name: CI/CD Pipeline - Feedback Analyzer

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          PYTHONPATH=. pytest

  docker-build-and-deploy:
    name: Build and Deploy Docker Image to Cloud Run
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: smart-feedback-analyzer-2025
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authorize Docker to push to Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/smart-feedback-analyzer-2025/feedback-analyzer-repo/feedback-analyzer .
          docker push us-central1-docker.pkg.dev/smart-feedback-analyzer-2025/feedback-analyzer-repo/feedback-analyzer

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy smart-feedback-api \
            --image us-central1-docker.pkg.dev/smart-feedback-analyzer-2025/feedback-analyzer-repo/feedback-analyzer \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
